repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        exclude: deprecated|deploy|venv
        args: [--python-version=3.11, --ignore-missing-imports,  --install-types, --non-interactive,]

  - repo: local
    hooks:
      # For reformatting code
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        args: [ --line-length=88, --target-version=py311 ]

      # For upgrade python code syntax for newer versions of the language
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: python
        types: [ python ]

      # Tool for automatically reordering python imports
      - id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: python
        types: [ python ]

       # Removes unused imports and unused variables from Python code
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

        # sort __all__ statements
      - id: sort-all
        name: Sort __all__ records
        description: Automatically Sort __all__ records alphabetically.
        entry: sort-all
        language: python
        types: [ python ]