# create config map
# for config.yaml
# and cookies.txt (optional)
apiVersion: v1
kind: ConfigMap
metadata:
  name: yt-notifier-config
  namespace: yt-notifier-namespace
data:
  config.yaml: |
    bot:
      token: XXXXXXXXXXXXXXXXXXXXX
    chat_id: -100XXXXXXXXXXXXXXXXX
    temp_chat_id: -100XXXXXXXXXXXX
    report:
      template: | 
          <h1>‚úÖ –°–ï–ô–ß–ê–° –í –≠–§–ò–†–ï:</h1>
          <br/>
          <ol type='1'>
          {% for channel in channels %}
              <li>
                  <b><a href='{{channel.url}}'>{{channel.label}}</a></b> <br/>
                  {% if channel.concurrent_view_count is not none %}
                      <b>üëÄ{{channel.concurrent_view_count}}</b>
                  {% endif %}
                  {% if channel.like_count is not none %}
                      <b>üëç{{channel.like_count}}</b>
                  {% endif %}
                  {% if channel.duration is not none %}
                      <b>üïë{{channel.duration}}</b>
                  {% endif %}
              </li>
              <br/>
          {% endfor %}
          </ol>
          <hr/>
          <i>üí¨ –ó–∞—Ö–æ–¥–∏—Ç–µ –≤ –Ω–∞—à <a href='https://t.me/Discordovchat'>—á–∞—Ç</a>.</i>
          <br/>
          <i>ü§ñ <a href='https://t.me/discordovo_feedback_bot'>–ë–æ—Ç-–ø—Ä–µ–¥–ª–æ–∂–∫–∞</a>, –ø—Ä–∏—Å—ã–ª–∞–π—Ç–µ –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã–µ —Å—Å—ã–ª–∫–∏ –Ω–∞ –∫–∞–Ω–∞–ª—ã/–≤–∏–¥–µ–æ/–∫–∞—Ä—Ç–∏–Ω–∫–∏. </i>
      empty: | 
        <b>ü§∑ –ò–Ω—Ç–µ—Ä–µ—Å–Ω—ã—Ö —Å—Ç—Ä–∏–º–æ–≤ —Å–µ–π—á–∞—Å –Ω–µ—Ç.</b>
        <hr/>
        <i>üí¨ –ó–∞—Ö–æ–¥–∏—Ç–µ –≤ –Ω–∞—à <a href='https://t.me/Discordovchat'>—á–∞—Ç</a>.</i>
        <br/>
        <i>ü§ñ <a href='https://t.me/discordovo_feedback_bot'>–ë–æ—Ç-–ø—Ä–µ–¥–ª–æ–∂–∫–∞</a>, –ø—Ä–∏—Å—ã–ª–∞–π—Ç–µ –∏–Ω—Ç–µ—Ä–µ—Å–Ω—ã–µ —Å—Å—ã–ª–∫–∏ –Ω–∞ –∫–∞–Ω–∞–ª—ã/–≤–∏–¥–µ–æ/–∫–∞—Ä—Ç–∏–Ω–∫–∏. </i>

    start_scheduler: True
    interval_s: 300
    # For notification from Twitch
    # You can obtain from https://dev.twitch.tv/console
    # twitch:
    #   app_id: xxxxxxxxxxxxxxxxxxxxxxxxxx
    #   app_secret: xxxxxxxxxxxxxxxxxxxxxxxxxx
    # Path to cookie file for youtube-dlp
    # youtube:
    #  cookies_filepath: /path/to/cookies.txt
  cookies.txt: |
    # Netscape HTTP Cookie File
    # This file is generated by yt-dlp.  Do not edit.