bot:
  token: 123456789:ABCDEFGHIJKLMOPRSTQYWZ

# Chat with posts from bot
chat_id: 123456789

# garbage chat, needed for delta-posting
temp_chat_id: 987654321

# Report customization
# With Jinja2 template you can access to ChanelDescription object via 'channel' variable
#
#class ChannelDescription(BaseModel):
#    url: str
#    label: str
#    like_count: Optional[int] = None
#    concurrent_view_count: Optional[int] = None
#    duration: Optional[str] = None
#
report:
  template: | 
      <h1>âœ… Ğ¡Ğ•Ğ™Ğ§ĞĞ¡ Ğ’ Ğ­Ğ¤Ğ˜Ğ Ğ•:</h1>
      <br/>
      <ol type='1'>
      {% for channel in channels %}
          <li>
              <b><a href='{{channel.url}}'>{{channel.label}}</a></b> <br/>
              {% if channel.concurrent_view_count is not none %}
                  <b>ğŸ‘€{{channel.concurrent_view_count}}</b>
              {% endif %}
              {% if channel.like_count is not none %}
                  <b>ğŸ‘{{channel.like_count}}</b>
              {% endif %}
              {% if channel.duration is not none %}
                  <b>ğŸ•‘{{channel.duration}}</b>
              {% endif %}
          </li>
          <br/>
      {% endfor %}
      </ol>
      <hr/>
      <i>ğŸ’¬ Ğ—Ğ°Ñ…Ğ¾Ğ´Ğ¸Ñ‚Ğµ Ğ² Ğ½Ğ°Ñˆ <a href='https://t.me/Discordovchat'>Ñ‡Ğ°Ñ‚</a></i>

  empty: | 
    <b>ğŸ¤· Ğ˜Ğ½Ñ‚ĞµÑ€ĞµÑĞ½Ñ‹Ñ… ÑÑ‚Ñ€Ğ¸Ğ¼Ğ¾Ğ² ÑĞµĞ¹Ñ‡Ğ°Ñ Ğ½ĞµÑ‚.</b>
    <hr/>
    <i>ğŸ’¬ Ğ—Ğ°Ñ…Ğ¾Ğ´Ğ¸Ñ‚Ğµ Ğ² Ğ½Ğ°Ñˆ <a href='https://t.me/Discordovchat'>Ñ‡Ğ°Ñ‚</a></i>

# Channel lists
# url must be ends with @user
channels:
  - label: Your label ğŸˆ
    url: https://www.youtube.com/@user

# interval between checks in seconds
interval_s: 60

